In [75]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns

In [76]:
train_ds=pd.read_csv('/kaggle/input/playground-series-s4e5/train.csv')
test_ds=pd.read_csv('/kaggle/input/playground-series-s4e5/test.csv')
train_ds.info(), test_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1117957 entries, 0 to 1117956
Data columns (total 22 columns):
 #   Column                           Non-Null Count    Dtype  
---  ------                           --------------    -----  
 0   id                               1117957 non-null  int64  
 1   MonsoonIntensity                 1117957 non-null  int64  
 2   TopographyDrainage               1117957 non-null  int64  
 3   RiverManagement                  1117957 non-null  int64  
 4   Deforestation                    1117957 non-null  int64  
 5   Urbanization                     1117957 non-null  int64  
 6   ClimateChange                    1117957 non-null  int64  
 7   DamsQuality                      1117957 non-null  int64  
 8   Siltation                        1117957 non-null  int64  
 9   AgriculturalPractices            1117957 non-null  int64  
 10  Encroachments                    1117957 non-null  int64  
 11  IneffectiveDisasterPreparedness  1117957 non-null 

(None, None)

In [77]:
count = np.isinf(train_ds).values.sum() 
count

0

In [78]:
train_ds

id  MonsoonIntensity  TopographyDrainage  RiverManagement  \
0              0                 5                   8                5   
1              1                 6                   7                4   
2              2                 6                   5                6   
3              3                 3                   4                6   
4              4                 5                   3                2   
...          ...               ...                 ...              ...   
1117952  1117952                 3                   3                4   
1117953  1117953                 2                   2                4   
1117954  1117954                 7                   3                9   
1117955  1117955                 7                   3                3   
1117956  1117956                 4                   5                6   

         Deforestation  Urbanization  ClimateChange  DamsQuality  Siltation  \
0                    8             6              4            4          3   
1                    4             8              8            3          5   
2                    7             3              7            1          5   
3                    5             4              8            4          7   
4                    6             4              4            3          3   
...                ...           ...            ...          ...        ...   
1117952             10             4              5            5          7   
1117953              3             9              5            8          1   
1117954              4             6              5            9          1   
1117955              7             5              2            3          4   
1117956              9             5              5            2          8   

         AgriculturalPractices  ...  DrainageSystems  CoastalVulnerability  \
0                            3  ...                5                     3   
1                            4  ...                7                     2   
2                            4  ...                7                     3   
3                            6  ...                2                     4   
4                            3  ...                2                     2   
...                        ...  ...              ...                   ...   
1117952                     10  ...                7                     8   
1117953                      3  ...                9                     4   
1117954                      3  ...                5                     5   
1117955                      6  ...                6                     8   
1117956                      4  ...                4                     8   

         Landslides  Watersheds  DeterioratingInfrastructure  PopulationScore  \
0                 3           5                            4                7   
1                 0           3                            5                3   
2                 7           5                            6                8   
3                 7           4                            4                6   
4                 6           6                            4                1   
...             ...         ...                          ...              ...   
1117952           7           2                            2                1   
1117953           4           3                            7                4   
1117954           5           5                            6                5   
1117955           5           3                            4                6   
1117956           6           5                            5                6   

         WetlandLoss  InadequatePlanning  PoliticalFactors  FloodProbability  
0                  5                   7                 3             0.445  
1                  3                   4                 3             0.450  
2                

In [79]:
train_ds.isna().sum()

id                                 0
MonsoonIntensity                   0
TopographyDrainage                 0
RiverManagement                    0
Deforestation                      0
Urbanization                       0
ClimateChange                      0
DamsQuality                        0
Siltation                          0
AgriculturalPractices              0
Encroachments                      0
IneffectiveDisasterPreparedness    0
DrainageSystems                    0
CoastalVulnerability               0
Landslides                         0
Watersheds                         0
DeterioratingInfrastructure        0
PopulationScore                    0
WetlandLoss                        0
InadequatePlanning                 0
PoliticalFactors                   0
FloodProbability                   0
dtype: int64

In [80]:
train_ds[train_ds.columns[1:]].corr()['FloodProbability'][ : ]

MonsoonIntensity                   0.189098
TopographyDrainage                 0.187635
RiverManagement                    0.187131
Deforestation                      0.184001
Urbanization                       0.180861
ClimateChange                      0.184761
DamsQuality                        0.187996
Siltation                          0.186789
AgriculturalPractices              0.183366
Encroachments                      0.178841
IneffectiveDisasterPreparedness    0.183109
DrainageSystems                    0.179305
CoastalVulnerability               0.177774
Landslides                         0.185346
Watersheds                         0.181907
DeterioratingInfrastructure        0.190007
PopulationScore                    0.185890
WetlandLoss                        0.183396
InadequatePlanning                 0.180968
PoliticalFactors                   0.182417
FloodProbability                   1.000000
Name: FloodProbability, dtype: float64

In [81]:
train_ds=train_ds.drop(['id'],axis=1)
test_ds=test_ds.drop(['id'],axis=1)

Memory  optimization

In [82]:
memory_usage=train_ds.memory_usage().sum()/1024**2
print("memory usage before optimization :{:.2f} MB".format(memory_usage))

memory usage before optimization :179.12 MB


In [83]:
memory_usage=test_ds.memory_usage().sum()/1024**2
print("memory usage before optimization :{:.2f} MB".format(memory_usage))

memory usage before optimization :113.72 MB


In [84]:
def memory_optimization(data_frame):
    memory_usage=data_frame.memory_usage().sum()/1024**2
    cols=data_frame.columns
    for col in cols:
        column_type=data_frame[col].dtype
        
        if column_type !=object:
            col_min=data_frame[col].min()
            col_max=data_frame[col].max()
            if str(column_type)[:3]=='int':
                if col_min > np.iinfo(np.int8).min and col_max< np.iinfo(np.int8).max:
                    data_frame[col]=data_frame[col].astype(np.int8)
                elif col_min > np.iinfo(np.int16).min and col_max< np.iinfo(np.int16).max:
                    data_frame[col]=data_frame[col].astype(np.int16)
                elif col_min > np.iinfo(np.int32).min and col_max< np.iinfo(np.int32).max:
                    data_frame[col]=data_frame[col].astype(np.int32)
                elif col_min > np.iinfo(np.int64).min and col_max< np.iinfo(np.int64).max:
                    data_frame[col]=data_frame[col].astype(np.int64)
            else:
                if col_min > np.finfo(np.float16).min and col_max< np.finfo(np.float16).max:
                    data_frame[col]=data_frame[col].astype(np.float16)
                elif col_min > np.finfo(np.float32).min and col_max< np.finfo(np.float32).max:
                    data_frame[col]=data_frame[col].astype(np.float32)
                else:
                    data_frame[col]=data_frame[col].astype(np.float64)
        else:
            data_frame[col]=data_frame[col].astype('object')
    mem_usage=data_frame.memory_usage().sum()/1024**2
    print("memory usage after optimization is: {:.2f} MB".format(mem_usage))
    print("memory usage reduce by: {:.2f}%".format(100*(memory_usage-mem_usage)/memory_usage))
    
    return data_frame

In [85]:
train=memory_optimization(train_ds)

memory usage after optimization is: 23.46 MB
memory usage reduce by: 86.90%


In [86]:
test=memory_optimization(test_ds)

memory usage after optimization is: 14.22 MB
memory usage reduce by: 87.50%


In [87]:
target=train['FloodProbability']
train=train.drop(['FloodProbability'],axis=1)

In [88]:
target

0          0.445068
1          0.449951
2          0.529785
3          0.535156
4          0.415039
             ...   
1117952    0.495117
1117953    0.479980
1117954    0.485107
1117955    0.495117
1117956    0.560059
Name: FloodProbability, Length: 1117957, dtype: float16

In [89]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from catboost import CatBoostRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [90]:
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.2, random_state=42)
rf = RandomForestRegressor(n_estimators=100, random_state=42)
ada = AdaBoostRegressor(n_estimators=100, random_state=42)
gb = GradientBoostingRegressor(n_estimators=100, random_state=42)
cat = CatBoostRegressor(iterations=100, learning_rate=0.1, random_state=42, verbose=0)


In [91]:
rf.fit(X_train, y_train)
ada.fit(X_train, y_train) 
gb.fit(X_train, y_train)
cat.fit(X_train, y_train)


/opt/conda/lib/python3.10/site-packages/numpy/lib/function_base.py:522: RuntimeWarning: overflow encountered in cast
  scl = avg_as_array.dtype.type(a.size/avg_as_array.size)


In [92]:
rf_pred = rf.predict(X_test)
ada_pred = ada.predict(X_test)
gb_pred = gb.predict(X_test)
cat_pred = cat.predict(X_test)


In [93]:
rf_pred,ada_pred,gb_pred,cat_pred

(array([0.51789307, 0.53150879, 0.53094971, ..., 0.51671387, 0.48656494,
        0.51625977]),
 array([0.52321768, 0.5857315 , 0.55747952, ..., 0.54211565, 0.50027357,
        0.52075918]),
 array([0.52644746, 0.53285575, 0.52821566, ..., 0.51148161, 0.50086037,
        0.51145691]),
 array([0.52731241, 0.56038134, 0.52556248, ..., 0.52342552, 0.49580122,
        0.50763541]))

In [94]:
rf_mse = mean_squared_error(y_test, rf_pred)
print("rf Mean Squared Error:", rf_mse)

ada_mse = mean_squared_error(y_test, ada_pred)
print("ada Mean Squared Error:", ada_mse)

gb_mse = mean_squared_error(y_test, gb_pred)
print("gb Mean Squared Error:", gb_mse)

cat_mse = mean_squared_error(y_test, cat_pred)
print("cat Mean Squared Error:", cat_mse)

rf Mean Squared Error: 0.0008944333847660526
ada Mean Squared Error: 0.0010779311182171059
gb Mean Squared Error: 0.0010023522426631348
cat Mean Squared Error: 0.0006180235250844109


In [95]:
predictions = cat.predict(test)
predictions

array([0.56003838, 0.47066791, 0.47016006, ..., 0.58190104, 0.54314524,
       0.50068789])

In [96]:
submission=pd.read_csv('/kaggle/input/playground-series-s4e5/sample_submission.csv')
submission=submission.drop(['FloodProbability'],axis=1)
submission['FloodProbability']=pd.DataFrame(predictions)
submission

id  FloodProbability
0       1117957          0.560038
1       1117958          0.470668
2       1117959          0.470160
3       1117960          0.474698
4       1117961          0.476059
...         ...               ...
745300  1863257          0.488783
745301  1863258          0.446535
745302  1863259          0.581901
745303  1863260          0.543145
745304  1863261          0.500688

[745305 rows x 2 columns]

In [97]:
submission.to_csv('Submission.csv', index=False)

In [98]:
submission.to_csv('./Submission.csv', index=False)